[package]
name = "dracon"
version = "0.1.0"
edition = "2021"
authors = ["Lingkang <contact@lingkang.dev>"]

[workspace]
members = ["raft", "server"]

[lib]
name = "raft"
path = "raft/src/lib.rs"

[dev-dependencies]
line_cracker = "0.1.1"

[[bin]]
name = "server"
path = "server/src/main.rs"

[dependencies]
rand = "0.8.5"
