[package]
name = "raft"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.21"
rand = "0.8.5"
tokio = { version = "1.36.0", features = [
    "rt",
    "io-util",
    "net",
    "time",
    "sync",
    "macros",
] }
