[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
raft = { path = "../raft" }
logger = { path = "../logger" }
log = { version = "0.4.21", features = ["std"] }
tokio = { version = "1.36.0", features = ["rt", "net"] }
