name: Cargo Build & Test

on:
  push:
    branches-ignore:
      - "doc*"
    paths:
      - "**.rs"
      - "Cargo.toml"
      - ".github/workflows/main.yml"

  schedule:
    - cron: '0 8 * * 5' # Runs at 08:00, only on Friday

  workflow_dispatch: # Manually run the workflow

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Set up Rust
        run: rustup update

      - name: Build 
        run: cargo build --verbose

      - name: Test
        run: cargo test --verbose --workspace

  linter_check:
    name: Rust Linter Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
