name: Generate Rust Doc
on:
  push:
    branches:
      - main
    paths:
      - "**.rs"
      - "Cargo.toml"
      - ".github/workflows/rustdoc.yml"

jobs:
  build:
    name: Generate Rust Doc
    runs-on: ubuntu-latest

    steps:
      - name: Checkout doc branch
        uses: actions/checkout@main
        with:
          ref: doc
          token: ${{ secrets.GH_PAT}}

      - name: Merge `main` into `doc`
        run: |
          git config user.name "GitHub Actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin main:main
          git merge main --allow-unrelated-histories -X theirs
          git commit --amend -m ":twisted_rightwards_arrows: Merge branch \`main\` into \`doc\`"

      - name: Update and Clean up
        run: |
          rustup update
          rm -rf ./docs/*
          git rm -r --cached ./docs
          cargo clean

      - name: Generate Rustdoc
        run: |
          cargo doc --package logger --no-deps --document-private-items
          cargo doc --package raft --no-deps --document-private-items
          cargo doc --package rpc --no-deps --document-private-items
          cargo doc --no-deps --document-private-items
          echo '<meta http-equiv="refresh" content="0; url=server/index.html">' > ./target/doc/index.html

      - name: Add and Commit Rustdoc
        run: |
          cp -r target/doc/* ./docs
          git add ./docs
          if [[ -n $(git status -s) ]]; then
            git commit -m ":memo: $(date --utc "+%Y-%m-%d %H:%M:%S.%2N")"
          fi
          git push -f https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git doc
        shell: bash
