name: Generate and deploy Rust doc
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Generate & deploy Rust doc
    runs-on: ubuntu-latest

    steps:
      - name: Checkout doc branch
        uses: actions/checkout@main
        with:
          ref: doc
          token: ${{ secrets.GH_PAT}}

      - name: Merge main into doc
        run: |
          git config user.name "GitHub Actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin main:main
          git merge main --allow-unrelated-histories

      - name: Generate Rustdoc
        run: |
          rustup update
          cargo doc --no-deps --document-private-items

      - name: Add and Commit Rustdoc
        run: |
          chmod +x ./docgen.sh
          ./docgen.sh
          git commit -am ":memo: $(date --utc "+%Y-%m-%d %H:%M:%S.%2N")"
          git push https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git doc
        shell: bash
